version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
            - appspec.yml
            - abc.sh
            - deploy-log.txt
discard-paths: yes
