version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
files:
- appspec.yml
- cron.yaml
- index.php
- logo_aws_reduced.gif
- scheduled.php
- styles.css 
